apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
      nodePort : 30071